### ISSUE TITLE
Allow the node to run in attached mode

### ISSUE THREAD

**Issue by bpierre** [aeternity/epoch#31] opened 2017-08-29 10:07 UTC
I was working on the Dockerfile PR for the previous version, and the fact that the node was running in the background only was making things a bit tricky with Docker.

If you decide to keep it this way, can we make this behavior optional? It might also simplify integration with systemd and other tools that manage processes.

As an example, nginx runs in the background by default, but allows to configure it [so it can run in the foreground](http://nginx.org/en/docs/ngx_core_module.html#daemon), which is [how the Docker image is running it](https://github.com/nginxinc/docker-nginx/blob/14aa3b1b80341099afbf90eb0a9b9061b7145f18/mainline/stretch/Dockerfile#L43).

**Comment by wagerlabs** [comment] 2017-08-29 10:21
I don't think this should be a problem. @sennui  ?

**Comment by sennui** [comment] 2017-08-30 08:26
@bpierre can you tell us more what causes issues when erlang is in the background?

Lets re-cap on the foreground/background for a bit. If something is foreground it means it runs in the context of shell -- which in general is not good.

The background operations mean that a program runs in its own process. Its much more robust solution. This is why most of server side software runs in the background as daemons.

In case of erlang software - this is simple to solve. The prod tarbal has standard layout of erlang release. There is always `PATH_TO_BIN start` command. If you call `PATH_TO_BIN console` it will run in so called interactive mode with erlang shell open and in the context of OS shell

All in all - easy to solve - but I would not encourage that approach

**Comment by bpierre** [comment] 2017-08-30 10:50
Sure!

> The background operations mean that a program runs in its own process. Its much more robust solution. This is why most of server side software runs in the background as daemons.

I agree that it’s an interesting feature, and that’s how nginx is running by default, while still allowing to run it in the foreground. It makes it easy to work with tools that need to manage processes themselves like Docker. The way Docker containers work is that when a process returns, the container stops immediately ([more about this here](https://docs.docker.com/engine/reference/run/#detached-vs-foreground)). That’s because Docker itself allows to run any container in the foreground (by default), in the background (using `-d`), to restart it automatically, execute another command, etc.

> In case of erlang software - this is simple to solve. The prod tarbal has standard layout of erlang release. There is always PATH_TO_BIN start command. If you call PATH_TO_BIN console it will run in so called interactive mode with erlang shell open and in the context of OS shell

Is `PATH_TO_BIN start` running in the background or the foreground?

I think it could be very useful to start the console when the Docker container is ran in interactive mode (`-it`), but it is generally something that programs themselves detect, rather than a Docker-specific thing. The Node.js Docker image works this way: if the container is ran with `docker run -it`, Node.js detects that it runs in a TTY context and starts the REPL.

It is also important to note that we are only talking about the default command here, Docker allows to change it very easily. For example, you can start an interactive shell in the container by passing `/bin/sh` as a command to start instead of `node`: `docker run -it node /bin/sh`.

To be clear, running it in foreground doesn’t have to be easy to do, nor to be the default way to start epoch, but having a possibility to start the process in the foreground, writing on STDOUT / STDERR, and also attaching the console could simplify things for tools like Docker or Unix in general. A way to do it could be to have a starting script, which could provide these features.

The Docker image could work this way:

- `docker run aeternity/epoch`: epoch starts in the foreground (inside the container), write logs to STDOUT / STDERR, and Docker redirects it (the Docker command doesn’t exit).
- `docker run aeternity/epoch -d`: same than before, except that Docker will run the container in the background. At this point, one could decide to attach the console for example: `docker exec <container_id> epoch attach`.
- `docker run -it aeternity/epoch`: our starting script will detect that a TTY is present and will run `PATH_TO_BIN console`.
- `docker run aeternity/epoch epoch --some --parameters` (assuming the name of the command is `epoch`): the default command is replaced and the user is free to decide what to run in the container. This is how parameters will be passed if needed.

Apart from the “production” Dockerfile, I think it could also be nice to provide a `docker-compose.yml` file for development, so that creating an environment to develop on epoch would be reduced to install Docker and running `docker-compose up` in the project directory. To make things simpler, we could just start an interactive shell, mounting the project directory in the Docker container, so that developers could manually type the commands they want.

**Comment by sennui** [comment] 2017-08-30 11:13
> Is PATH_TO_BIN start running in the background or the foreground?

start is the background work (daemon)
console is the forground work

OK, I think I know what you mean. Basically the daemon approach was caused by trying to be independent from tools like `screen` or `nohop`. 

All we need then is have the docker run the `epoch` peer as `console` and this is up to maintainer of the top layer host to decide if he wants docker foreground or background.

Agree we can have couple docker composes. They could call dev/test configs.

**Comment by bpierre** [comment] 2017-08-30 12:34
> All we need then is have the docker run the epoch peer as console and this is up to maintainer of the top layer host to decide if he wants docker foreground or background.

Sounds good to me.

> Agree we can have couple docker composes. They could call dev/test configs.

👍

**Comment by dincho** [comment] 2018-01-22 15:52
@bpierre Could you please check our docker image `docker pull aetrnty/epoch` and let me know if that works good enough for you to close this issue?

**Comment by evdoks** [comment] 2018-02-08 10:46
Closing as resolved (and not active).

**Closed by evdoks** 2018-02-08 10:46 UTC
Labels: community, enhancement, question
